//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusBites.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CampusBites.Web.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string Add_to_cart {
            get {
                return ResourceManager.GetString("Add to cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string Admin_Dashboard {
            get {
                return ResourceManager.GetString("Admin Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Tools.
        /// </summary>
        public static string Admin_Tools {
            get {
                return ResourceManager.GetString("Admin Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Orders Report.
        /// </summary>
        public static string All_Orders_Report {
            get {
                return ResourceManager.GetString("All Orders Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing address.
        /// </summary>
        public static string Billing_address {
            get {
                return ResourceManager.GetString("Billing address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string Change_your_account_settings {
            get {
                return ResourceManager.GetString("Change your account settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string Clear_All {
            get {
                return ResourceManager.GetString("Clear All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm &amp; Pay.
        /// </summary>
        public static string Confirm___Pay {
            get {
                return ResourceManager.GetString("Confirm & Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to shopping.
        /// </summary>
        public static string Continue_to_shopping {
            get {
                return ResourceManager.GetString("Continue to shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Role.
        /// </summary>
        public static string Create_New_Role {
            get {
                return ResourceManager.GetString("Create New Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string Create_Role {
            get {
                return ResourceManager.GetString("Create Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Placed.
        /// </summary>
        public static string Date_Placed {
            get {
                return ResourceManager.GetString("Date Placed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit name.
        /// </summary>
        public static string Edit_name {
            get {
                return ResourceManager.GetString("Edit name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmed.
        /// </summary>
        public static string Email_Confirmed {
            get {
                return ResourceManager.GetString("Email Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string Enddate {
            get {
                return ResourceManager.GetString("Enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Roles.
        /// </summary>
        public static string Existing_Roles {
            get {
                return ResourceManager.GetString("Existing Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to excel.
        /// </summary>
        public static string Export_to_excel {
            get {
                return ResourceManager.GetString("Export to excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string Export_to_pdf {
            get {
                return ResourceManager.GetString("Export to pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lockout Enabled .
        /// </summary>
        public static string Lockout_Enabled_ {
            get {
                return ResourceManager.GetString("Lockout Enabled ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Menu Items.
        /// </summary>
        public static string Manage_Menu_Items {
            get {
                return ResourceManager.GetString("Manage Menu Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Permissions.
        /// </summary>
        public static string Manage_Permissions {
            get {
                return ResourceManager.GetString("Manage Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Roles.
        /// </summary>
        public static string Manage_Roles {
            get {
                return ResourceManager.GetString("Manage Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string Manage_Users {
            get {
                return ResourceManager.GetString("Manage Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        public static string Manage_your_account {
            get {
                return ResourceManager.GetString("Manage your account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Order History.
        /// </summary>
        public static string My_Order_History {
            get {
                return ResourceManager.GetString("My Order History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Role Name.
        /// </summary>
        public static string New_Role_Name {
            get {
                return ResourceManager.GetString("New Role Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string Order_ID {
            get {
                return ResourceManager.GetString("Order ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Ref.
        /// </summary>
        public static string Pay_Ref {
            get {
                return ResourceManager.GetString("Pay Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Payment_Method {
            get {
                return ResourceManager.GetString("Payment Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Data.
        /// </summary>
        public static string Personal_Data {
            get {
                return ResourceManager.GetString("Personal Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Checkout.
        /// </summary>
        public static string Proceed_to_Checkout {
            get {
                return ResourceManager.GetString("Proceed to Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Order Status Updates via Email.
        /// </summary>
        public static string Receive_Order_Status_Updates_via_Email {
            get {
                return ResourceManager.GetString("Receive Order Status Updates via Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string Recent_Activity {
            get {
                return ResourceManager.GetString("Recent Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required for mobile money.
        /// </summary>
        public static string Required_for_mobile_money {
            get {
                return ResourceManager.GetString("Required for mobile money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        public static string Revenue {
            get {
                return ResourceManager.GetString("Revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Summary.
        /// </summary>
        public static string SalesSummary {
            get {
                return ResourceManager.GetString("SalesSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string Sector {
            get {
                return ResourceManager.GetString("Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping address.
        /// </summary>
        public static string Shipping_address {
            get {
                return ResourceManager.GetString("Shipping address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string Street_Address {
            get {
                return ResourceManager.GetString("Street Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (RWF).
        /// </summary>
        public static string Total__RWF_ {
            get {
                return ResourceManager.GetString("Total (RWF)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        public static string Update_password {
            get {
                return ResourceManager.GetString("Update password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all orders report.
        /// </summary>
        public static string View_all_orders_report {
            get {
                return ResourceManager.GetString("View all orders report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string View_Details {
            get {
                return ResourceManager.GetString("View Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for updates...
        /// </summary>
        public static string Waitingforupdates__ {
            get {
                return ResourceManager.GetString("Waitingforupdates..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        public static string Your_account_contains_personal_data_that_you_have_given_us__This_page_allows_you_to_download_or_delete_that_data_ {
            get {
                return ResourceManager.GetString("Your account contains personal data that you have given us. This page allows you " +
                        "to download or delete that data.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart.
        /// </summary>
        public static string Your_cart {
            get {
                return ResourceManager.GetString("Your cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Shopping Cart.
        /// </summary>
        public static string Your_Shopping_Cart {
            get {
                return ResourceManager.GetString("Your Shopping Cart", resourceCulture);
            }
        }
    }
}
